---
X_No_Archive: Yes
abstract: 'Perl implementation of the libp2p networking stack'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Test2::Plugin::UTF8: '0'
  Test2::Tools::Compare: '0'
  Test2::V0: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
  perl: v5.40.0
dynamic_config: 1
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150012'
keywords: []
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Libp2p
no_index:
  directory:
    - t
    - xt
    - share
    - eg
  file: []
  namespace: []
  package: []
optional_features:
  TLS:
    description: 'TLS 1.3 Support'
    requires:
      IO::Socket::SSL: '0'
      Net::SSLeay: '0'
  dnsaddr:
    description: "dnsaddr is a protocol that instructs the resolver to lookup multiaddr(s) in DNS TXT records for the domain name in it's value section."
    requires:
      Net::DNS: '0'
provides:
  Libp2p:
    file: lib/Libp2p.pm
    version: v0.1.0
  Libp2p::ConnectionManager:
    file: lib/Libp2p/ConnectionManager.pm
  Libp2p::Crypto:
    file: lib/Libp2p/Crypto.pm
  Libp2p::Crypto::PublicKeyMsg:
    file: lib/Libp2p/Crypto.pm
  Libp2p::Future:
    file: lib/Libp2p/Future.pm
    version: v0.0.1
  Libp2p::Host:
    file: lib/Libp2p/Host.pm
    version: v0.0.1
  Libp2p::IO:
    file: lib/Libp2p/IO.pm
    version: v0.0.1
  Libp2p::Loop:
    file: lib/Libp2p/Loop.pm
    version: v0.0.1
  Libp2p::Multiaddr:
    file: lib/Libp2p/Multiaddr.pm
    version: v0.0.1
  Libp2p::Muxer::Yamux:
    file: lib/Libp2p/Muxer/Yamux.pm
    version: v0.0.1
  Libp2p::Muxer::Yamux::Stream:
    file: lib/Libp2p/Muxer/Yamux.pm
    version: v0.0.1
  Libp2p::PeerID:
    file: lib/Libp2p/PeerID.pm
  Libp2p::PeerStore:
    file: lib/Libp2p/PeerStore.pm
    version: v0.0.1
  Libp2p::ProtoBuf:
    file: lib/Libp2p/ProtoBuf.pm
    version: v0.0.1
  Libp2p::ProtoBuf::Message:
    file: lib/Libp2p/ProtoBuf/Message.pm
    version: v0.0.1
  Libp2p::Protocol::AutoNAT:
    file: lib/Libp2p/Protocol/AutoNAT.pm
    version: v0.0.1
  Libp2p::Protocol::AutoNAT::V1::Message:
    file: lib/Libp2p/Protocol/AutoNAT.pm
  Libp2p::Protocol::AutoNAT::V1::Message::Dial:
    file: lib/Libp2p/Protocol/AutoNAT.pm
  Libp2p::Protocol::AutoNAT::V1::Message::Peer:
    file: lib/Libp2p/Protocol/AutoNAT.pm
  Libp2p::Protocol::AutoNAT::V1::Message::Response:
    file: lib/Libp2p/Protocol/AutoNAT.pm
  Libp2p::Protocol::AutoNAT::V2::Message::DialRequest:
    file: lib/Libp2p/Protocol/AutoNAT.pm
    version: v0.0.1
  Libp2p::Protocol::DHT::Message::Record:
    file: lib/Libp2p/Protocol/DHT.pm
    version: v0.0.1
  Libp2p::Protocol::Identify:
    file: lib/Libp2p/Protocol/Identify.pm
    version: v0.0.1
  Libp2p::Protocol::Identify::Message:
    file: lib/Libp2p/Protocol/Identify.pm
  Libp2p::Protocol::Noise:
    file: lib/Libp2p/Protocol/Noise.pm
    version: v0.0.1
  Libp2p::Protocol::Noise::HandshakePayload:
    file: lib/Libp2p/Protocol/Noise.pm
    version: v0.0.1
  Libp2p::Protocol::Noise::SecureStream:
    file: lib/Libp2p/Protocol/Noise.pm
    version: v0.0.1
  Libp2p::Protocol::TLS::ASN1:
    file: lib/Libp2p/Protocol/TLS.pm
    version: v0.0.1
  Libp2p::Protocol::TLS::SecureStream:
    file: lib/Libp2p/Protocol/TLS.pm
    version: v0.0.1
  Libp2p::ResourceManager:
    file: lib/Libp2p/ResourceManager.pm
    version: v0.0.1
  Libp2p::Stream:
    file: lib/Libp2p/Stream.pm
    version: v0.0.1
  Libp2p::Utils:
    file: lib/Libp2p/Utils.pm
    version: v0.0.1
recommends:
  IO::Socket::SSL: '0'
  Net::DNS: '0'
  Net::SSLeay: '0'
requires:
  Algorithm::Kademlia: v1.1.1
  Crypt::PK::Ed25519: '0'
  Errno: '0'
  Math::BigInt: '0'
  Noise: '0'
  Scalar::Util: '0'
  Socket: '0'
resources:
  bugtracker: https://github.com/sanko/Net-Libp2p.pm/issues
  homepage: https://github.com/sanko/Net-Libp2p.pm
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/Net-Libp2p.pm.git
version: v0.1.0
x_custom_builder: 0
x_help_wanted:
  - Tester
  - Documenter
x_ignore:
  - .tidyallrc
  - .gitignore
  - .clang-format
  - .github/**
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
