---
abstract: 'Perl implementation of the libp2p networking stack'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
  perl: v5.40.0
dynamic_config: 1
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150012'
keywords: []
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Libp2p
no_index:
  directory: []
  file: []
  namespace: []
  package: []
provides:
  Libp2p:
    file: lib/Libp2p.pm
    version: v0.0.1
  Libp2p::Future:
    file: lib/Libp2p/Future.pm
    version: v0.1.0
  Libp2p::IO:
    file: lib/Libp2p/IO.pm
    version: v0.2.0
  Libp2p::Loop:
    file: lib/Libp2p/Loop.pm
    version: v0.1.0
  Libp2p::Stream:
    file: lib/Libp2p/Stream.pm
    version: v0.2.0
  Libp2p::Utils:
    file: lib/Libp2p/Utils.pm
    version: v0.0.1
  Libp2p::Yamux:
    file: lib/Libp2p/Yamux.pm
    version: v0.0.1
requires:
  Crypt::PK::Ed25519: '0'
  Errno: '0'
  Math::BigInt: '0'
  Scalar::Util: '0'
  Socket: '0'
  Net::Libp2p::ConnectionManager:
    file: lib/Libp2p/ConnectionManager.pm
  Net::Libp2p::Crypto:
    file: lib/Libp2p/Crypto.pm
  Net::Libp2p::Host:
    file: lib/Libp2p/Host.pm
    version: v0.1.0
  Net::Libp2p::Multiaddr:
    file: lib/Libp2p/Multiaddr.pm
    version: v0.2.0
  Net::Libp2p::PeerID:
    file: lib/Libp2p/PeerID.pm
  Net::Libp2p::PeerStore:
    file: lib/Libp2p/PeerStore.pm
    version: v0.1.2
  Net::Libp2p::ProtoBuf:
    file: lib/Libp2p/ProtoBuf.pm
    version: v0.2.0
  Net::Libp2p::ResourceManager:
    file: lib/Libp2p/ResourceManager.pm
    version: v0.1.0
resources:
  bugtracker: https://github.com/sanko/Net-Libp2p.pm/issues
  homepage: https://github.com/sanko/Net-Libp2p.pm
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/Net-Libp2p.pm.git
version: v0.0.1
x_custom_builder: 0
x_ignore:
  - .tidyallrc
  - .gitignore
  - .clang-format
  - .github/**
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
